-- Budget Solution Cloud schema.  No RLS or policies are defined here.
create extension if not exists pgcrypto;

create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = timezone('utc', now()); return new; end $$;

create table if not exists public.profiles (
  id text primary key, auth_user_id uuid unique references auth.users(id) on delete set null,
  name text not null, initials text not null, profile_picture text,
  created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now())
);
create table if not exists public.roles (id bigserial primary key, name text not null unique, is_admin boolean not null default false, is_approver boolean not null default false);
create table if not exists public.permissions (id text primary key, user_id text not null unique references public.profiles(id) on delete cascade, can_create_years boolean not null default false, can_edit_all_pages boolean not null default false, can_add_categories boolean not null default false, can_clear_data boolean not null default false, restricted_pages text not null default '', updated_at timestamptz not null default timezone('utc', now()));
create table if not exists public.profile_roles (user_id text primary key references public.profiles(id) on delete cascade, role_id bigint references public.roles(id) on delete cascade, is_admin boolean not null default false, is_approver boolean not null default false);

create table if not exists public.budget_years (id text primary key, year integer not null unique check (year between 1900 and 2200), created_at timestamptz not null default timezone('utc', now()), created_by text references public.profiles(id) on delete set null);
create table if not exists public.categories (id text primary key, name text not null unique, type text not null check (type in ('Cost','Revenue','Mixed')), description text not null default '', sort_order integer not null default 0, parent_category_id text references public.categories(id) on delete set null, is_parent boolean not null default false, collapsed boolean not null default false, created_at timestamptz not null default timezone('utc', now()), created_by text references public.profiles(id) on delete set null);
create table if not exists public.year_categories (year integer not null references public.budget_years(year) on delete cascade, category_id text not null references public.categories(id) on delete cascade, primary key(year, category_id));
create table if not exists public.budget_entries (id text primary key, user_id text not null references public.profiles(id) on delete cascade, category_id text not null references public.categories(id) on delete cascade, year integer not null references public.budget_years(year) on delete cascade, month integer not null check (month between 1 and 12), value numeric(18,2) not null default 0, updated_at timestamptz not null default timezone('utc', now()), updated_by text references public.profiles(id) on delete set null, unique(user_id, category_id, year, month));
create table if not exists public.category_order (user_id text not null references public.profiles(id) on delete cascade, category_id text not null references public.categories(id) on delete cascade, sort_order integer not null default 0, primary key(user_id, category_id));
create table if not exists public.row_notes (id text primary key, user_id text not null references public.profiles(id) on delete cascade, category_id text not null references public.categories(id) on delete cascade, year integer not null references public.budget_years(year) on delete cascade, note text not null default '', author_name text not null default '', updated_at timestamptz not null default timezone('utc', now()), unique(user_id, category_id, year));

create table if not exists public.page_comments (id text primary key, page_user_id text not null references public.profiles(id) on delete cascade, year integer not null references public.budget_years(year) on delete cascade, author_id text not null references public.profiles(id) on delete cascade, author_name text not null, author_initials text not null, parent_id text references public.page_comments(id) on delete cascade, comment text not null, created_at timestamptz not null default timezone('utc', now()));
create table if not exists public.page_status (id text primary key, page_user_id text not null references public.profiles(id) on delete cascade, year integer not null references public.budget_years(year) on delete cascade, status text not null default 'draft' check (status in ('draft','submitted','validated')), submitted_at timestamptz, submitted_by text references public.profiles(id) on delete set null, validated_at timestamptz, validated_by text references public.profiles(id) on delete set null, unique(page_user_id, year));
create table if not exists public.audit_log (id text primary key, timestamp timestamptz not null default timezone('utc', now()), user_id text references public.profiles(id) on delete set null, user_name text, budget_page text, year integer, category_id text references public.categories(id) on delete set null, category_name text, field text, previous_value text, new_value text, action text not null);

create table if not exists public.remuneration_config (id text primary key, user_id text not null unique references public.profiles(id) on delete cascade, monthly_payments integer not null default 14, iht_rate numeric(8,5) not null default .25, meal_allowance_days integer not null default 220, holiday_allowance_month integer not null default 6 check (holiday_allowance_month between 1 and 12), christmas_allowance_month integer not null default 12 check (christmas_allowance_month between 1 and 12), updated_at timestamptz not null default timezone('utc', now()));
create table if not exists public.remuneration_ftes (id text primary key, user_id text not null references public.profiles(id) on delete cascade, year integer not null default 2026 references public.budget_years(year) on delete restrict, position integer not null default 0, role text not null default '', collaborator_name text not null default '', annual_base_salary numeric(18,2) not null default 0, meal_allowance_day numeric(18,2) not null default 0, indexation_pct numeric(8,5) not null default 0, increase_pct numeric(8,5) not null default 0, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()));
create table if not exists public.export_history (id text primary key, version integer not null, timestamp timestamptz not null default timezone('utc', now()), exported_by text references public.profiles(id) on delete set null, exported_by_name text, year integer not null, filename text not null, filepath text not null, snapshot jsonb not null, export_mode text not null default 'from');

create index if not exists idx_budget_entries_user_year on public.budget_entries(user_id, year);
create index if not exists idx_budget_entries_category on public.budget_entries(category_id);
create index if not exists idx_audit_log_timestamp on public.audit_log(timestamp);
create index if not exists idx_categories_order on public.categories(sort_order);
create index if not exists idx_page_comments_page_year on public.page_comments(page_user_id, year);
create index if not exists idx_remuneration_ftes_user_year on public.remuneration_ftes(user_id, year);

drop trigger if exists profiles_updated_at on public.profiles; create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists permissions_updated_at on public.permissions; create trigger permissions_updated_at before update on public.permissions for each row execute function public.set_updated_at();
drop trigger if exists budget_entries_updated_at on public.budget_entries; create trigger budget_entries_updated_at before update on public.budget_entries for each row execute function public.set_updated_at();
drop trigger if exists row_notes_updated_at on public.row_notes; create trigger row_notes_updated_at before update on public.row_notes for each row execute function public.set_updated_at();
drop trigger if exists remuneration_config_updated_at on public.remuneration_config; create trigger remuneration_config_updated_at before update on public.remuneration_config for each row execute function public.set_updated_at();
drop trigger if exists remuneration_ftes_updated_at on public.remuneration_ftes; create trigger remuneration_ftes_updated_at before update on public.remuneration_ftes for each row execute function public.set_updated_at();
